name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm test